### ISSUE TITLE
[BUG] - substr($item['name'], 0, 35) will prevent shipment creation if the last character is a special character

### ISSUE THREAD

**Issue by CsSatter** [dpdconnect/magento2-shipping#11]
Example product name: PRODUIT D’ORIGINE
2 pcs Filtre à charbon pour cave à vin Liebherr 909634200

https://github.com/dpdconnect/magento2-shipping/blob/master/Helper/Services/OrderConvertService.php#L316

When you place an order with a product with that name the module can't encode the data needed to make the API call to DPD.

**Comment by dpdplugin** [comment]
This will be fixed in the next release but a solution would be to change it to mb_substr
