### ISSUE TITLE
Trying to print a label gives bad credentials. Password saved in Config settings

### ISSUE THREAD

**Issue by onepack** [dpdconnect/magento2-shipping#13]
M2.3.4
PHP 7.2

[2020-04-29 10:25:52] main.CRITICAL: Bad credentials {"exception":"[object] (DpdConnect\\Sdk\\Exceptions\\AuthenticateException(code: 0): Bad credentials at /home/user/domains/domain.com/public_html/vendor/dpdconnect/php-sdk/src/Common/ResponseError.php:66)"} []

I'm able to login with the same credentials via:
https://api.dpdconnect.nl/swagger  
Also via Postman.

I checked the IP for api.dpdconnect.nl what is 34.90.184.113 and seems to be google.
Whitelisted the IP and I pinged the IP from the webshop server. No package loss.

What can be the cause of this?

Logging only gives me "bad credentials".

**Comment by onepack** [comment]
The same on a testing environment with a different IP. "Bad credentials".

**Comment by dpdplugin** [comment]
Hi,
This means that the account isn't properly configured for DPDConnect.
It is best to ask you're account manager to activate the account for DIS 2.1 and DPDConnect
