### ISSUE TITLE
Backend form validation for configuration

### ISSUE THREAD

**Issue by johannessmit** [dpdconnect/magento2-shipping#15]
Hello,

I've ran into an issue that return label's weren't generated without any feedback on the backend besides that the RMA couldn't be saved.
After digging in the logs I found the following error:
```
    [0] => This value is too long. It should have 35 characters or less.
```

This could be easily fixed by validating the length of the inputs on the configuration pages :)

**Comment by dpdplugin** [comment]
Thank you for the feedback, I have passed it on to the developers.
