### ISSUE TITLE
Condition name always set to "package_weight" for DPD Pickup

### ISSUE THREAD

**Issue by ArjenMiedema** [dpdconnect/magento2-shipping#16]
### Prerequisites:
* Magento v2.3.5-p1
* DPD Magento 2 Shipping v1.1.0

### Steps to reproduce:
* Go to Stores > Configuration
* Go to the Shipping Methods and select DPD Pickup
* Set the condition to "Package vs Destination"
* Upload a valid tablerate CSV file
* Check the values in the database

### Expected results:
* The field "condition_name" should be set to "package_value_with_discount"
* The field "condition_name" should be able to store at least 27 chars (default Magento is 30)

### Actual results:
* The field "condition_name" is set to "package_weight"
* The field "condition_name" can only contain 20 characters, so "package_value_with_discount" will never fit

### Temporary fix I provided for my project:
* I changed the length of the "condition_name" field to 30 characters
* I manually changed the value to "package_value_with_discount", but this will be undone with the next CSV import that is done

**Comment by dpdplugin** [comment]
Thank you for reporting this.
It has been solved in the newest version.
