### ISSUE TITLE
undefined offset

### ISSUE THREAD

**Issue by akosglue** [dpdconnect/magento2-shipping#2]
issue from the other module remains also in this module:
https://github.com/DPDBeNeLux/magento2-shipping/issues/32

**Comment by akosglue** [comment]
without a google api key, the error message is still 'no address found'.

**Comment by akosglue** [comment]
any updates about this issue?

**Comment by dpdplugin** [comment]
You will get this error when the geocoding key isn't correct.
Please make sure the geocoding api is configured correctly, you can test you're key using the following link.
https://maps.googleapis.com/maps/api/geocode/json?key=YOUR_API_KEY&components=country:BE|postal_code:1040
