### ISSUE TITLE
DPD - There are no shipping labels generated.

### ISSUE THREAD

**Issue by Ylmzef** [dpdconnect/magento2-shipping#21]
I can't generate labels from Magento.
There no any logs avaible about that.

**Comment by dpdplugin** [comment]
Hi @Ylmzef,

What errors are you experiencing exactly?

**Comment by Ylmzef** [comment]
Hi @dpdplugin 

I got following error message from Magento backend;
![image](https://user-images.githubusercontent.com/8562514/95113332-9725b980-0742-11eb-9843-bd57ac53feb6.png)

I'm trying to create the label for a order with Magento "Free Shipping" methode.
Is it possible ?

**Comment by dpdplugin** [comment]
It is only possible to generate shipping labels for orders placed with the DPD shipping methods.
A free shipping alternative would be to use table rates.

**Comment by Ylmzef** [comment]
I have too many products and some of them are not suitable for DPD as weight and size.
