### ISSUE TITLE
Feature request - Parcelshop select on manual orders

### ISSUE THREAD

**Issue by mikehenze** [dpdconnect/magento2-shipping#25]
Right now only fronted orders can use pickup points.
Please allow this for backend also.

**Comment by Ylmzef** [comment]
I have already requested : https://github.com/dpdconnect/magento2-shipping/issues/21

**Comment by mikehenze** [comment]
@Ylmzef It is not the same request

**Comment by dpdplugin** [comment]
Thank you for the feedback, I have passed it on to the developers.
