### ISSUE TITLE
no validation

### ISSUE THREAD

**Issue by akosglue** [dpdconnect/magento2-shipping#3]
It is possible to place an order with DPD parcel shop method, but without selecting an actual delivery point. So that the order is visible in the back-end but it is unknown where to deliver.
This can happen in the blank theme. (with Aheadworks onestepcheckout)

**Comment by akosglue** [comment]
any updates about this issue?

**Comment by dpdplugin** [comment]
Hi @akosglue 
This is a bug with the onestepcheckout module and has been documented internally.
When using the default checkout validation is there.
![image](https://user-images.githubusercontent.com/32730624/69964734-3078b380-1513-11ea-805b-fbacb38a1407.png)
