### ISSUE TITLE
Bad Credentials error

### ISSUE THREAD

**Issue by shalinikat** [dpdconnect/magento2-shipping#30]
{"0":"Bad credentials","1":"

#1 DpdConnect\Sdk\Resources\Authentication->processRequest(array(401, '{"code":401,"mes...')) called at [vendor/dpdconnect/php-sdk/src/Resources/Authentication.php:61]\n#2

I got this error. May I know what causes this error.

**Comment by dpdplugin** [comment]
That error means the credentials aren't correctly entered in the DPD module.
Please make sure DPD enabled the credentials for DPD Connect

**Comment by shalinikat** [comment]
No, My credentials are correct the issue comes with php sdk , May I know is
there any specific reason that the details are not authenticated?
