### ISSUE TITLE
Is there _any_ documentation and/or debugging mode possible?

### ISSUE THREAD

**Issue by Asitis** [dpdconnect/magento2-shipping#36]
I must say I have had zero positive experiences with any DPD module ever, but I had hopes this 'new one' would be better. Sadly, again, can't get it to work at all. I set everything up, but it just doesn't do anything and I see no clear way to even find out why. In the configuration there is no option for a debug mode to show errors, there are no logs being created, so now I'm going through every file trying to figure it out myself.

It would help if there is any documentation at all. Am I missing something?

**Comment by dpdplugin** [comment]
A documentation page is currently under development, in the meanwhile you can contact the developers by reaching out to your account manager.
