### ISSUE TITLE
Missing function GetToken error on checkout page

### ISSUE THREAD

**Issue by adrianalin89** [dpdconnect/magento2-shipping#45]
I've updated my module to latest version(1.2) and when going to the checkout page a error brakes the php from Model/CheckoutConfigProvider line 100 where getToken function is called on the class DPDClient.
Looking in the class there is no such function declared.

**Comment by adrianalin89** [comment]
https://github.com/dpdconnect/magento2-shipping/blob/master/Model/CheckoutConfigProvider.php
`use DpdConnect\Shipping\Helper\DPDClient;`

`public function __construct(
       ...,
        DPDClient $client,
       .....
    ) {
        ......
        $this->client = $client;
        ......
    }`

`public function getConfig()
    {
     .......
        $output['dpd_parcelshop_token'] = $this->client->authenticate()->getToken()->getPublicJWTToken(
            $this->dpdSettings->getValue(DpdSettings::ACCOUNT_USERNAME),
            $this->crypt->decrypt($this->dpdSettings->getValue(DpdSettings::ACCOUNT_PASSWORD))
        );
.......`

**Comment by dpdplugin** [comment]
Hi @adrianalin89 ,
The getToken function is inherited from the SDK.
Did you install the module in the app/code folder?
If so, you still need to update the SDK using:
`composer update dpdconnect/php-sdk`
