### ISSUE TITLE
Google Maps popup not showing

### ISSUE THREAD

**Issue by mvsteenb** [dpdconnect/magento2-shipping#5]
When clicking on 'DPD Pickup', the parcelshop selector is not loaded. 
![parcelshop](https://user-images.githubusercontent.com/57991905/69238354-12689600-0b98-11ea-9ee6-54c4cc3e78bf.PNG)

**Comment by akosglue** [comment]
any updates about this issue?

**Comment by mvsteenb** [comment]
No, no response from the developers. It's still not working for me :-(

**Comment by dpdplugin** [comment]
Hi @mvsteenb 
Are you sure you have the maps javascript api and the geocoding api enabled for the google api key?

**Comment by mvsteenb** [comment]
Yes both the Geocoding & Javascript API's are enabled

**Comment by mvsteenb** [comment]
We are getting the following errors:

![image](https://user-images.githubusercontent.com/57991905/70237850-55199900-1768-11ea-9a2f-de74eec6ea3a.png)

**Comment by opalice** [comment]
Same problem without any error on inspect

![Checkout](https://user-images.githubusercontent.com/9999027/78972638-820efb80-7b0e-11ea-900b-caf67ca030c9.jpg)

**Comment by dpdplugin** [comment]
Do you get results if you check your key with the following link?
https://maps.googleapis.com/maps/api/geocode/json?key=YOUR_API_KEY&components=country:BE|postal_code:1040

**Comment by mikehenze** [comment]
I have the same issue.
The result are correct when using a direct maps.googleapis.com url
m2.3.5-p1
dpd shipping 1.1.1

**Comment by mikehenze** [comment]
@mvsteenb Are you testing this on a dev server ?

**Comment by mvsteenb** [comment]
Yes, we test on a development server. The map is still not loading after installing the latest version.

**Comment by mikehenze** [comment]
Me too. So it could be related to the google maps api not able to connect due to a rights issue.
Are you using hypernode by any change?

**Comment by mvsteenb** [comment]
I haven't put any restrictions on my API key. 

No, we are running on Google cloud VM

**Comment by mikehenze** [comment]
The restriction could be on the hosting site because its a dev server.
Anyway it would be nice if @dpdplugin would pick this up.

**Comment by mvsteenb** [comment]
There is no difference between our dev & production server. As we are running on Google cloud, I would expect that the Google maps API should work :-)

**Comment by mvsteenb** [comment]
> Do you get results if you check your key with the following link?
> [https://maps.googleapis.com/maps/api/geocode/json?key=YOUR_API_KEY&components=country:BE|postal_code:1040](https://maps.googleapis.com/maps/api/geocode/json?key=YOUR_API_KEY&components=country:BE%7Cpostal_code:1040)

Yes, this works fine

**Comment by mvsteenb** [comment]
I have posted this question in November last year guys. Can someone please provide some support ?

**Comment by dpdplugin** [comment]
Please update to the latest version, this should fix the problem.

**Comment by mikehenze** [comment]
Version 1.1.4 does not fix this.

**Comment by lewisvoncken** [comment]
@mikehenze 
Just log the result which is returned in the get geo location to see if your api token is valid.
And did you already see which of the to notices are returned because the given error is thrown at 2 places

**Comment by mikehenze** [comment]
Switched to sendcloud some time ago

**Comment by YachYaroslav** [comment]
@dpdplugin Token is expired problem with google maps now showing (500 error response).

I guess the problem is with `$this->cache->save($jwtToken, 'dpdconnect_jwt_token');`.
So, token is saved into cache and DPD Client reads this from the cache when it might be already expired.

My version is the latest at the moment: 1.1.6.

**Comment by YachYaroslav** [comment]
I get the next response when it tries to fetch dpd parcels:

```
{"message":"Input Validation Failure","logref":"6037cccd292ad","_links":{"self":{"href":"http:\\/\\/api.dpdconnect.nl\\/api\\/connect\\/v1\\/parcelshop?countryIso=NL\\u0026latitude=52.3493918\\u0026limit=20\\u0026longitude=4.9196969\\u0026with_count=0"},"about":{"href":"http:\\/\\/api.dpdconnect.nl\\/api\\/connect\\/v1.yml","title":"Api Specification"}},"_embedded":{"errors":[{"message":"token has expired","code":null,"_links":{"self":{"href":"http:\\/\\/api.dpdconnect.nl\\/api\\/connect\\/v1.yml"}}}]}}
```

**Comment by YachYaroslav** [comment]
@dpdplugin question: how long your JWT token is valid? I think your developers have to past a valid token lifetime value to `$this->cache->save(...` as the third parameter. Right now Magento 2 default value is used.
