### ISSUE TITLE
fixing Warning: file_put_contents(/tmp/dpd/dpd-products)

### ISSUE THREAD

**Issue by alghaspour** [dpdconnect/magento2-shipping#52]
Hi,
If your global system tmp dir is not writable for your app username you will get following error and the checkout process does not proceed ,

main.CRITICAL: Warning: file_put_contents(/tmp/dpd/dpd-products): failed to open stream: Permission denied in /vendor/dpdconnect/php-sdk/src/Resources/Product.php on line 78

you can change sys_get_temp_dir() value on your php configuration or simply comment it and define writable directory.
and create /home/[appuser]/public_html/var/tmp/dpd/ manually,

new storeCachedList function looks like :

  private function storeCachedList($products, $query)
    {
    /*
        if (!file_exists(sys_get_temp_dir() . '/dpd/')) {
            mkdir(sys_get_temp_dir() . '/dpd/');
        }
        $filename = sys_get_temp_dir() .'/dpd/dpd-products';
   */
        $filename = '/home/[appuser]/public_html/var/tmp/dpd/dpd-products';
        file_put_contents($filename, serialize($products));
    }

**Comment by dpdplugin** [comment]
Hi @alghaspour ,
Thanks for the info, but I think this is a server configuration error and not an error of the DPD module.
The method you are mentioning is a method of the SDK.
I will therefore be closing this issue.
