### ISSUE TITLE
Compatibility with Magento 2.4.4 and PHP 8.1

### ISSUE THREAD

**Issue by Davie82** [dpdconnect/magento2-shipping#53]
Currently I am upgrading to Magento 2.4.4. When running `bin/magento setup:di:compile` I get the following error:

```
PHP Deprecated:  Optional parameter $shipment declared before required parameter $packages is implicitly treated as a required parameter in /vendor/dpdconnect/magento2-shipping/Helper/Services/OrderConvertService.php on line 196
```

Magento version: 2.4.4
Module version: 1.2.3
PHP version: 8.1

**Comment by dpdplugin** [comment]
Hi @Davie82 We already have an update ready.
We will release it in the comming days.
