### ISSUE TITLE
Cannot download package with composer

### ISSUE THREAD

**Issue by dev-awevo** [dpdconnect/magento2-shipping#6]
Hello, 

I can install the module with composer. When I try I get this error : 

> Could not find package dpdconnect/magento2-shipping at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

If I install the module without composer, I get a 500 errors when I'm in order process and I choose dpd pickup

>  PHP Fatal error:  Uncaught Error: Class 'DpdConnect\Sdk\Client' not found in app/code/DpdConnect/Shipping/Helper/DPDClient.php:82

Magento version : 2.2.9

Regards

**Comment by dev-awevo** [comment]
No answer?
Your sales department tells us to install this module, but it doesn't work.
Can you answer me quickly, my client is waiting on a module compatible with his DPD contract.

Regards,

**Comment by dpdplugin** [comment]
Hi,
An official release should be released soon, in the meantime please run this command:
Composer require  dpdconnect/magento2-shipping:1.0.7-beta
