### ISSUE TITLE
Wrong namespace

### ISSUE THREAD

**Issue by sergiozt** [dpdconnect/magento2-shipping#60]
In the latest 1.2.6 version the bug was introduced:
`DpdConnect\Shipping\Model\Attribute\Backend\ShippingDescription does not exist`
**Reason:**
In the files classes
https://github.com/dpdconnect/magento2-shipping/blob/1.2.6/Model/Attribute/Source/ShippingType.php#L3
and 
https://github.com/dpdconnect/magento2-shipping/blob/1.2.6/Model/Attribute/Backend/ShippingDescription.php#L3

the namespace started with **DPD**Connect however it has to be with lower cased  **Dpd**Connect

**Comment by dpdplugin** [comment]
Hi @sergiozt ,

Thanks for letting us know!
This has been fixed in 1.2.7.
