### ISSUE TITLE
Error during delivery methods load

### ISSUE THREAD

**Issue by MaxselNL** [dpdconnect/magento2-shipping#65]
[2022-12-21T17:14:13.353755+00:00] main.CRITICAL: Exception: Warning: Undefined array key "token" in /home/......./vendor/dpdconnect/php-sdk/src/Common/AuthenticatedHttpClient.php on line 77

Magento 2.4.5
PHP 8.1
DPD Latest version

**Comment by igorsKolcinsMagebit** [comment]
Temporary workaround:


File::method:
`\DpdConnect\Shipping\Block\Adminhtml\System\Carrier\DpdCustomerProductSettings::getCustomerProducts`

```
+ try {
    $products = $this->DPDClient->authenticate()->getProduct()->getList();
+ } catch (\Exception $exception) {
+   return [];
+ }

return array_filter($products, function ($product) {
    return in_array($product['type'], ['b2b', 'predict']);
});
```

**Comment by dpdplugin** [comment]
Hi,
This means the product endpoint is not enabled in the DPD webservice for your account, please contact your DPD account manager to solve this issue.

**Comment by igorsKolcinsMagebit** [comment]
@dpdplugin theoretically if the token is not generated or some error comes from the DPD side, it can throw the same error. If not mistaken there are 12 files that call `$this->DPDClient->authenticate()`, and theoretically, they are all not catching errors or do any validations before `getProducts()`
