### ISSUE TITLE
PHP 8.2 deprecated usages

### ISSUE THREAD

**Issue by hostep** [dpdconnect/magento2-shipping#77]
Hi there

Using:
- PHP 8.2
- Magento 2.4.6-p1
- dpdconnect/magento2-shipping 1.3.1

When I check using PHPStan version 1.10.21 (https://github.com/phpstan/phpstan), which is installed as a dev dependency in each Magento project, for PHP 8.2 deprecated usage of [creation of dynamic property](https://www.php.net/manual/en/migration82.deprecated.php#migration82.deprecated.core.dynamic-properties), I'm noticing some potential problems:

```
$ vendor/bin/phpstan analyse --level=0 vendor/dpdconnect/ | grep 'Access to an undefined property'
 182/182 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

  195    Access to an undefined property DpdConnect\Shipping\Model\ResourceModel\Tablerate::$readFactory.
  336    Access to an undefined property DpdConnect\Shipping\Model\ResourceModel\Tablerate::$importWebsiteId.
  337    Access to an undefined property DpdConnect\Shipping\Model\ResourceModel\Tablerate::$importUniqueHash.
  338    Access to an undefined property DpdConnect\Shipping\Model\ResourceModel\Tablerate::$importErrors.
  339    Access to an undefined property DpdConnect\Shipping\Model\ResourceModel\Tablerate::$importedRows.
  341    Access to an undefined property DpdConnect\Shipping\Model\ResourceModel\Tablerate::$readFactory.
  429    Access to an undefined property DpdConnect\Shipping\Model\ResourceModel\Tablerate::$importErrors.
  447    Access to an undefined property DpdConnect\Shipping\Model\ResourceModel\Tablerate::$importErrors.
  456    Access to an undefined property DpdConnect\Shipping\Model\ResourceModel\Tablerate::$importErrors.
  484    Access to an undefined property $this(DpdConnect\Shipping\Model\ResourceModel\Tablerate)::$importErrors.
  497    Access to an undefined property DpdConnect\Shipping\Model\ResourceModel\Tablerate::$importUniqueHash.
  499    Access to an undefined property DpdConnect\Shipping\Model\ResourceModel\Tablerate::$importWebsiteId.
  26     Access to an undefined property DpdConnect\Sdk\Resources\Authentication::$httpClient.
  58     Access to an undefined property DpdConnect\Sdk\Resources\Authentication::$httpClient.
```

I haven't tested if we can actually trigger these errors in Magento yet, but it wouldn't surprise me.

Note that 2 problems are released to the [SDK package](https://github.com/dpdconnect/php-sdk), but since this package is stuck on a particular version of the SDK, I'm going to leave it here, unless you want me to open a new issue as well over there?

Fixing these is probably not hard, so would be nice if this could happen soon-ish.

Thanks!

**Comment by hostep** [comment]
Hey @dpdplugin

Any ETA on when you're going to look into the 2 PR's I send in, in scope of this ticket? It will make your module workable on PHP 8.2 in combination with Magento 2.4.6

Thanks!

**Comment by emilev79** [comment]
Is this still the case? We will be starting our staging soon for the upgrade from 2.3 . Would be nice to know if this is going to work

**Comment by hostep** [comment]
@emilev79: yes, DPD hasn't answered on this thread or processed any of the PR's that were created to fix this, I think this module is kind of dead ...

For one of our clients, we agreed with them to move to a different shipping provider and for another client we patched the dpd modules with the fixes from the PR's:
- https://github.com/dpdconnect/php-sdk/pull/24
- https://github.com/dpdconnect/magento2-shipping/pull/78

**Comment by hostep** [comment]
Looks like DPD eventually fixed it themselves 3 months ago (even though there were PR's created with fixes by the community for 6 months).

Issues presented in this ticket got fixed in:
- version 1.3.2 of the magento2-shipping module: https://github.com/dpdconnect/magento2-shipping/commit/3cc7ebccd2c5a8e9e9c0176b06f9462bb224c540
- version 1.1.12 of the php-sdk: https://github.com/dpdconnect/php-sdk/commit/fddabc2c5f24b98033b15d0125e3217aab440e94

Anyway, let's close this ticket now...
