### ISSUE TITLE
New Tracking Urls

### ISSUE THREAD

**Issue by vacla** [dpdconnect/magento2-shipping#89]
We received an email that the tracking url changed, is there anything that needs to be changed in the module?
![18e3652e-393f-48ee-a0dd-85da8efe0884](https://github.com/dpdconnect/magento2-shipping/assets/10290022/463a6852-1be3-415b-9bb2-ecf3b93da855)

**Comment by vacla** [comment]
@dpdplugin any update on this?

**Comment by dpdplugin** [comment]
If you update to the latest version, this is fixed
