### ISSUE TITLE
Undefined array key "token" in /vendor/dpdconnect/php-sdk/src/Common/AuthenticatedHttpClient.php on line 84

### ISSUE THREAD

**Issue by Kishorchhugani** [dpdconnect/magento2-shipping#99]
we configured the Account Settings at Sales menu but when we are trying to open delivery methods section we are facing below error : 

1 exception(s):
Exception #0 (Exception): Warning: Undefined array key "token" in /vendor/dpdconnect/php-sdk/src/Common/AuthenticatedHttpClient.php on line 84

we are using Magento Version 2.4.7-p2 and php version 8.2

any help regarding this issue ?

Thank you.

**Comment by edwinbos** [comment]
Same issue on 2.4.6-p2 and PHP version 8.1

**Comment by edwinbos** [comment]
That could be, but the module should not break the complete:
- Shipping methods configuration page
- Cart page
- Checkout page

**Comment by dpdplugin** [comment]
Agree, thats why its on our development board optimisations.
